export type Item = { id: string; name: string; type: 'raw' | 'product' }
export type Ingredient = { itemId: string; amount: number }
export type Recipe = { id: string; name: string; duration: number; power: number; inputs: Ingredient[]; outputs: Ingredient[] }
export type Registry = { source: string; items: Item[]; recipes: Recipe[] }
export type Target = { itemId: string; value: number; mode: 'minimum' | 'exact' }
export type Supply = { itemId: string; limit: number | null }
export type Solution = { rates: Record<string, number>; sources: Record<string, number>; net: Record<string, number>; power: number; loss: number; iterations: number }
export type NodeId = `item:${string}` | `recipe:${string}`
export type Point = { x: number; y: number }
